name: soongsil_data_mining
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.6
  - pandas
  - matplotlib
  - IPython
  - ipyleaflet
  - ipywidgets
  - requests
  - jupyter
  - numpy==1.16.2
  - scipy==1.2.1
  - scikit-learn==0.20.3
